import org.junit.Test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by terabyte on 23/12/2014.
 */
public class TestApplication {
	
	
	private String stackScript = new StringBuilder().append("#!/bin/bash \n").append("#install puppet\n")

	.append("IPADDR=$(/sbin/ifconfig eth0 | awk '/inet / { print $2 }' | sed 's/addr://')\n")

	.append("# This updates the packages on the system from the distribution repositories. \n")
			.append("apt-get update \n").append("apt-get upgrade -y\n")

	.append("# This section sets the hostname.\n").append("echo $HOSTNAME > /etc/hostname\n")
			.append("hostname -F /etc/hostname\n")

	.append("# This section sets the Fully Qualified Domain Name (FQDN) in the hosts file.\n")
			.append("echo $IPADDR $FQDN $HOSTNAME >> /etc/hosts\n")

	.append("wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb\n")
			.append("sudo dpkg -i puppetlabs-release-trusty.deb\n").append("sudo apt-get update\n")
			.append("apt-get -q -y install puppet\n")

	.append("#install modules\n").append("#execute config node 'myhost' {}\n")
			.append("puppet module install puppetlabs-stdlib\n").append("puppet module install puppetlabs-java\n")
			.append("puppet module install puppetlabs-mongodb\n").append("puppet module install attachmentgenie-ufw\n")
			.append("puppet module install netmanagers-fail2ban\n").append("puppet module install example42-timezone\n")
			.append("puppet module install domcleal/augeasproviders\n")
			.append("puppet module install maestrodev-wget\n")
			.append("puppet module install danielburrell-gitartifact\n")

	.append("mkdir -p /opt/solong/infrastructure/\n")
			.append("wget --header=\"Authorization: token f8e4dd64743e3d5fa0f8c298a1174f009c5ae177\" -O infrastructure https://api.github.com/repos/danielburrell/infrastructure/tarball/\n")
			.append("tar xf infrastructure -C /opt/solong/infrastructure --strip-components=1\n")
			.append("rm infrastructure\n")

	.append("puppet apply /opt/solong/infrastructure/pyro/pyro.pp\n").toString();

	@Test
	public void test() throws IOException {
		SimpleProvisioner s = new SimpleProvisioner();
		Config config = new Config();
		config.setRam(1024);
		config.setRegion("london");
		config.setName("heavy");
		config.setOs("Ubuntu 14.04 LTS");
		// set stackscript info
		config.setStackScriptPublic(false);
		config.setStackScriptLabel("provision_heavy");
		config.setStackScriptDescription("provisions heavy");
		config.setStackScript(stackScript);
		config.setStackScriptRevisionNote("Autogenerated Script");
		List<Disk> disks = new ArrayList<Disk>();
		Disk e = new Disk();
		e.setSize(18000);
		e.setLabel("os");
		e.setPrimary(true);
		e.setReadOnly(false);
		e.setType("ext4");
		disks.add(e);
		config.setDisks(disks);
		s.buildFirstTime(config);

	}

}
